resolver: lts-8.21
compiler: ghcjs-0.2.1.9008021_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008021_ghc-8.0.2:
        url: https://github.com/achirkin/prepare-ghcjs/releases/download/lts-8.21-20170716/ghcjs-0.2.1.9008021_ghc-8.0.2.tar.gz
        sha1: c38434ee74c840525e14b494a1ecf565322c7153

packages:
  - '.'
  # Matrices, vectors, and geometry
  - location:
      git: https://github.com/achirkin/easytensor.git
      commit: 5d2628378e0075f2e2dba5125917ea44b17f8270
    subdirs:
      - dimensions
      - easytensor
    extra-dep: true
  # WebGL functions
  - location:
      git: https://github.com/achirkin/ghcjs-webgl.git
      commit: 4052509def345f96dd6f33d0dba736e45d776bff
    extra-dep: true
  # pointer events and animation frames for reflex
  - location:
      git: https://github.com/achirkin/reflex-animated.git
      commit: fd43f31bfb9614818e6791fa67a0ef3e8d3e4145
    extra-dep: true
  # DOM components for reflex platform
  - location:
      git: https://github.com/reflex-frp/reflex-dom.git
      commit: 07d94800289d268fb5145f5a2fac8318b64c3b3e
    subdirs:
      - reflex-dom-core
      - reflex-dom
    extra-dep: true
  # reflex engine
  - location:
      git: https://github.com/reflex-frp/reflex.git
      commit: a1092192c61f3dec924a8e2686dfe3440681bab3
    extra-dep: true
  # faster text via jsstring
  #- location:
  #    git: https://github.com/obsidiansystems/text.git
  #    commit: e9a5dca15cb5b96ac434aa21db18907383db25a2
  #  extra-dep: true
  - location:
       git: https://github.com/achirkin/qua-kit.git
       commit: 110014d6abb44e3f9d50ca4a7feb642ac25f1d92
    subdirs:
       - libs/hs/qua-types
    extra-dep: true

ghc-options:
  reflex: -O2 -dedupe
  reflex-dom-core: -O2 -dedupe
  reflex-dom: -O2 -dedupe
  reflex-animated: -O2
  ghcjs-webgl: -O2 -dedupe
  easytensor: -O2 -dedupe

flags:
  reflex:
    expose-all-unfoldings: true
    specialize-to-spidertimeline-global: true
  reflex-dom:
    use-reflex-optimizer: true
    expose-all-unfoldings: true
  reflex-dom-core:
    expose-all-unfoldings: true

extra-deps:
  - dependent-sum-template-0.0.0.6
  - ghcjs-dom-0.9.0.0
  - jsaddle-0.9.2.1
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - ghcjs-dom-jsffi-0.9.0.0
